name: Sync DockerHub README

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/sync-readme.yml
  workflow_dispatch:

env:
  IMAGE_NAME: md2confluence

jobs:
  sync-dh-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DH_USER }}
        password: ${{ secrets.DH_TOKEN }}
        repository: ${{ secrets.DH_USER }}/${{ env.IMAGE_NAME }}
        readme-filepath: ./README.md
        short-description: ${{ github.event.repository.description }}